"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LANGUAGE_STORAGE_KEY = "manah_arogya_language_v1";

export const LANGUAGE_OPTIONS = [
  { code: "en", label: "English" },
  { code: "hi", label: "हिन्दी" },
  { code: "mr", label: "मराठी" },
];

const translations = {
  "Info": { hi: "जानकारी", mr: "माहिती" },
  "Display Language": { hi: "दिखाने की भाषा", mr: "दर्शविण्याची भाषा" },
  "Choose how text appears across the platform.": {
    hi: "पूरे प्लेटफ़ॉर्म पर टेक्स्ट किस भाषा में दिखे, यह चुनें।",
    mr: "संपूर्ण प्लॅटफॉर्मवर मजकूर कोणत्या भाषेत दिसेल ते निवडा.",
  },
  "Notifications": { hi: "सूचनाएं", mr: "सूचना" },
  "Mark all read": { hi: "सभी को पढ़ा हुआ चिह्नित करें", mr: "सर्व वाचलेले म्हणून चिन्हांकित करा" },
  "No new notifications": { hi: "कोई नई सूचना नहीं", mr: "नवीन सूचना नाहीत" },
  "User": { hi: "उपयोगकर्ता", mr: "वापरकर्ता" },
  "Signed in as": { hi: "इस रूप में साइन इन", mr: "या नावाने साइन इन" },
  "Guest": { hi: "अतिथि", mr: "अतिथी" },
  "Dashboard": { hi: "डैशबोर्ड", mr: "डॅशबोर्ड" },
  "Logout": { hi: "लॉगआउट", mr: "लॉगआउट" },
  "Login / Sign up": { hi: "लॉगिन / साइन अप", mr: "लॉगिन / साइन अप" },
  "Overview": { hi: "सारांश", mr: "आढावा" },
  "Habit Tracker": { hi: "आदत ट्रैकर", mr: "सवय ट्रॅकर" },
  "AI Assistant": { hi: "एआई सहायक", mr: "एआय सहाय्यक" },
  "Therapy Room": { hi: "थेरेपी रूम", mr: "थेरपी रूम" },
  "Exercises": { hi: "अभ्यास", mr: "व्यायाम" },
  "Resources": { hi: "संसाधन", mr: "संसाधने" },
  "Appointments": { hi: "अपॉइंटमेंट", mr: "अपॉइंटमेंट" },
  "Events": { hi: "इवेंट्स", mr: "कार्यक्रम" },
  "Community": { hi: "समुदाय", mr: "समुदाय" },
  "My Profile": { hi: "मेरा प्रोफाइल", mr: "माझे प्रोफाइल" },
  "Admin Panel": { hi: "एडमिन पैनल", mr: "अ‍ॅडमिन पॅनल" },
  "Therapist Panel": { hi: "थेरपिस्ट पैनल", mr: "थेरपिस्ट पॅनल" },
  "Help & Support": { hi: "मदद और सहयोग", mr: "मदत आणि सहाय्य" },
  "Loading...": { hi: "लोड हो रहा है...", mr: "लोड होत आहे..." },
  "Practitioner": { hi: "प्रैक्टिशनर", mr: "प्रॅक्टिशनर" },
  "Administrator": { hi: "प्रशासक", mr: "प्रशासक" },
  "Sign Out": { hi: "साइन आउट", mr: "साइन आउट" },
  "Loading Therapist Panel...": { hi: "थेरपिस्ट पैनल लोड हो रहा है...", mr: "थेरपिस्ट पॅनल लोड होत आहे..." },
  "Patients": { hi: "मरीज", mr: "रुग्ण" },
  "Messages": { hi: "संदेश", mr: "संदेश" },
  "Loading Admin Panel...": { hi: "एडमिन पैनल लोड हो रहा है...", mr: "अ‍ॅडमिन पॅनल लोड होत आहे..." },
  "Users": { hi: "उपयोगकर्ता", mr: "वापरकर्ते" },
  "Moderation": { hi: "मॉडरेशन", mr: "मॉडरेशन" },
  "Therapists": { hi: "थेरपिस्ट", mr: "थेरपिस्ट" },
  "Alerts": { hi: "अलर्ट्स", mr: "अलर्ट" },
  "Dashboard": { hi: "डैशबोर्ड", mr: "डॅशबोर्ड" },
  "Understand what’s happening, why, and what to do next.": {
    hi: "समझें क्या हो रहा है, क्यों हो रहा है, और आगे क्या करना है।",
    mr: "काय घडत आहे, का घडत आहे आणि पुढे काय करायचे हे समजून घ्या.",
  },
  "Failed to load dashboard": { hi: "डैशबोर्ड लोड नहीं हो सका", mr: "डॅशबोर्ड लोड करता आला नाही" },
  "Practitioner Interface": { hi: "प्रैक्टिशनर इंटरफेस", mr: "प्रॅक्टिशनर इंटरफेस" },
  "This general wellness dashboard is designed for patients. Visit your dedicated Therapist panel to manage your schedule, accept appointments, and maintain clinical notes.": {
    hi: "यह सामान्य वेलनेस डैशबोर्ड मरीजों के लिए बनाया गया है। अपना शेड्यूल संभालने, अपॉइंटमेंट स्वीकार करने और क्लिनिकल नोट्स रखने के लिए अपने समर्पित थेरपिस्ट पैनल पर जाएं।",
    mr: "हा सर्वसाधारण वेलनेस डॅशबोर्ड रुग्णांसाठी आहे. तुमचे वेळापत्रक व्यवस्थापित करण्यासाठी, अपॉइंटमेंट स्वीकारण्यासाठी आणि क्लिनिकल नोंदी ठेवण्यासाठी तुमच्या थेरपिस्ट पॅनलवर जा.",
  },
  "Go to Therapist Portal": { hi: "थेरपिस्ट पोर्टल पर जाएं", mr: "थेरपिस्ट पोर्टलकडे जा" },
  "Coming Soon": { hi: "जल्द आ रहा है", mr: "लवकरच" },
  "Talk to our AI Voice Agents": { hi: "हमारे एआई वॉइस एजेंट्स से बात करें", mr: "आमच्या एआय व्हॉइस एजंट्सशी बोला" },
  "Quick Exercise": { hi: "त्वरित अभ्यास", mr: "झटपट व्यायाम" },
  "Do a quick breathing reset": { hi: "जल्दी से श्वास अभ्यास करें", mr: "झटपट श्वसन रीसेट करा" },
  "Assessment Overview": { hi: "असेसमेंट सारांश", mr: "मूल्यमापन आढावा" },
  "Retake Test": { hi: "टेस्ट फिर से दें", mr: "चाचणी पुन्हा घ्या" },
  "No completed assessment yet": { hi: "अभी तक कोई पूरा असेसमेंट नहीं", mr: "अद्याप कोणतेही पूर्ण मूल्यमापन नाही" },
  "Start a test to generate your first score summary and AI feedback.": {
    hi: "अपना पहला स्कोर सारांश और एआई फीडबैक पाने के लिए टेस्ट शुरू करें।",
    mr: "तुमचा पहिला स्कोअर सारांश आणि एआय फीडबॅक मिळवण्यासाठी चाचणी सुरू करा.",
  },
  "Recent Attempts": { hi: "हाल के प्रयास", mr: "अलीकडील प्रयत्न" },
  "Your assessment history will appear here.": { hi: "आपका असेसमेंट इतिहास यहां दिखाई देगा।", mr: "तुमचा मूल्यमापन इतिहास येथे दिसेल." },
  "Initial Assessment": { hi: "प्रारंभिक असेसमेंट", mr: "प्रारंभिक मूल्यमापन" },
  "Retake Assessment": { hi: "असेसमेंट फिर से", mr: "मूल्यमापन पुन्हा" },
  "Risk & Trend": { hi: "जोखिम और ट्रेंड", mr: "जोखीम आणि ट्रेंड" },
  "Risk Level": { hi: "जोखिम स्तर", mr: "जोखीम पातळी" },
  "Mood Trend": { hi: "मूड ट्रेंड", mr: "मूड ट्रेंड" },
  "7-Day Averages": { hi: "7-दिन का औसत", mr: "7-दिवसीय सरासरी" },
  "Mood Score": { hi: "मूड स्कोर", mr: "मूड स्कोअर" },
  "Habits Done": { hi: "पूरी आदतें", mr: "पूर्ण सवयी" },
  "Your Story (Last 7 Days)": { hi: "आपकी कहानी (पिछले 7 दिन)", mr: "तुमची कहाणी (मागील 7 दिवस)" },
  "No data": { hi: "डेटा नहीं", mr: "डेटा नाही" },
  "Identified Focus": { hi: "पहचाना गया फोकस", mr: "ओळखलेले लक्ष" },
  "No specific focus identified yet.": { hi: "अभी कोई विशेष फोकस नहीं पहचाना गया।", mr: "अजून कोणतेही विशिष्ट लक्ष ओळखले गेलेले नाही." },
  "What’s Happening (& Why)": { hi: "क्या हो रहा है (और क्यों)", mr: "काय घडत आहे (आणि का)" },
  "Explanations": { hi: "व्याख्या", mr: "स्पष्टीकरणे" },
  "Next Actions": { hi: "अगले कदम", mr: "पुढील कृती" },
  "Take Action": { hi: "कदम उठाएं", mr: "कृती करा" },
  "Exercise for you": { hi: "आपके लिए अभ्यास", mr: "तुमच्यासाठी व्यायाम" },
  "4-7-8 Breathing": { hi: "4-7-8 श्वास अभ्यास", mr: "4-7-8 श्वसन" },
  "Breathe": { hi: "सांस लें", mr: "श्वास घ्या" },
  "Start": { hi: "शुरू करें", mr: "सुरू करा" },
  "1. Inhale for 4s": { hi: "1. 4 सेकंड तक सांस लें", mr: "1. 4 सेकंद श्वास घ्या" },
  "2. Hold for 7s": { hi: "2. 7 सेकंड रोकें", mr: "2. 7 सेकंद थांबा" },
  "3. Exhale for 8s": { hi: "3. 8 सेकंड छोड़ें", mr: "3. 8 सेकंद श्वास सोडा" },
  "Follow the rhythm of the circle to quickly lower anxiety.": {
    hi: "चिंता जल्दी कम करने के लिए वृत्त की लय का पालन करें।",
    mr: "चिंता पटकन कमी करण्यासाठी वर्तुळाच्या लयीचे अनुसरण करा.",
  },
  "Recommended Resources": { hi: "सुझाए गए संसाधन", mr: "शिफारस केलेली संसाधने" },
  "Guide": { hi: "गाइड", mr: "मार्गदर्शक" },
  "Wellness": { hi: "वेलनेस", mr: "वेलनेस" },
  "Read": { hi: "पढ़ें", mr: "वाचा" },
  "No resources matched right now": { hi: "अभी कोई संसाधन मेल नहीं खा रहा", mr: "सध्या कोणतीही संसाधने जुळली नाहीत" },
  "Check back later or complete a quick check-in to get new, personalized recommendations.": {
    hi: "बाद में फिर देखें या नई व्यक्तिगत सिफारिशों के लिए त्वरित चेक-इन पूरा करें।",
    mr: "नंतर पुन्हा तपासा किंवा नवीन वैयक्तिक शिफारशींसाठी झटपट चेक-इन पूर्ण करा.",
  },
  "Complete Check-in": { hi: "चेक-इन पूरा करें", mr: "चेक-इन पूर्ण करा" },
  "Appointments": { hi: "अपॉइंटमेंट", mr: "अपॉइंटमेंट" },
  "book confidential sessions, track upcoming appointments, and reschedule quickly.": {
    hi: "गोपनीय सत्र बुक करें, आने वाली अपॉइंटमेंट ट्रैक करें और जल्दी से रीशेड्यूल करें।",
    mr: "गोपनीय सत्र बुक करा, पुढील अपॉइंटमेंटचा मागोवा घ्या आणि पटकन पुन्हा वेळ ठरवा.",
  },
  "Failed to load appointments.": { hi: "अपॉइंटमेंट लोड नहीं हो सकीं।", mr: "अपॉइंटमेंट लोड करता आल्या नाहीत." },
  "Select a counselor first.": { hi: "पहले एक काउंसलर चुनें।", mr: "प्रथम एक समुपदेशक निवडा." },
  "Please choose a preferred slot.": { hi: "कृपया पसंदीदा स्लॉट चुनें।", mr: "कृपया पसंतीचा स्लॉट निवडा." },
  "Select a slot before rescheduling.": { hi: "रीशेड्यूल से पहले स्लॉट चुनें।", mr: "पुन्हा वेळ ठरवण्यापूर्वी स्लॉट निवडा." },
  "Therapist Portal": { hi: "थेरपिस्ट पोर्टल", mr: "थेरपिस्ट पोर्टल" },
  "This booking page is designed for patients. Visit your dedicated Therapist Dashboard to view and manage your scheduled appointments.": {
    hi: "यह बुकिंग पेज मरीजों के लिए बनाया गया है। अपनी निर्धारित अपॉइंटमेंट देखने और प्रबंधित करने के लिए अपने समर्पित थेरपिस्ट डैशबोर्ड पर जाएं।",
    mr: "हे बुकिंग पृष्ठ रुग्णांसाठी आहे. तुमच्या नियोजित अपॉइंटमेंट पाहण्यासाठी आणि व्यवस्थापित करण्यासाठी तुमच्या थेरपिस्ट डॅशबोर्डवर जा.",
  },
  "Go to Therapist Dashboard": { hi: "थेरपिस्ट डैशबोर्ड पर जाएं", mr: "थेरपिस्ट डॅशबोर्डकडे जा" },
  "Session Center": { hi: "सेशन सेंटर", mr: "सत्र केंद्र" },
  "Your next session is ready": { hi: "आपका अगला सत्र तैयार है", mr: "तुमचे पुढील सत्र तयार आहे" },
  "Plan your next wellness session": { hi: "अपना अगला वेलनेस सत्र तय करें", mr: "तुमचे पुढील वेलनेस सत्र नियोजित करा" },
  "Choose a counselor, confirm a slot, and keep your appointments organized in one place.": {
    hi: "काउंसलर चुनें, स्लॉट कन्फर्म करें और अपनी अपॉइंटमेंट एक ही जगह व्यवस्थित रखें।",
    mr: "समुपदेशक निवडा, स्लॉट निश्चित करा आणि तुमच्या अपॉइंटमेंट एकाच ठिकाणी व्यवस्थित ठेवा.",
  },
  "Current profile": { hi: "वर्तमान प्रोफाइल", mr: "सध्याचे प्रोफाइल" },
  "Wellness Member": { hi: "वेलनेस सदस्य", mr: "वेलनेस सदस्य" },
  "No email synced": { hi: "कोई ईमेल सिंक नहीं", mr: "ईमेल सिंक नाही" },
  "This profile name is shared with booking and AI chat context.": {
    hi: "यह प्रोफाइल नाम बुकिंग और एआई चैट संदर्भ में साझा किया जाता है।",
    mr: "हे प्रोफाइल नाव बुकिंग आणि एआय चॅट संदर्भात वापरले जाते.",
  },
  "Total Sessions": { hi: "कुल सत्र", mr: "एकूण सत्रे" },
  "Booked": { hi: "बुक की गई", mr: "बुक झालेले" },
  "Rescheduled": { hi: "रीशेड्यूल", mr: "पुन्हा ठरवलेले" },
  "Available Counselors": { hi: "उपलब्ध काउंसलर", mr: "उपलब्ध समुपदेशक" },
  "Select a counselor to enable booking.": { hi: "बुकिंग शुरू करने के लिए काउंसलर चुनें।", mr: "बुकिंग सुरू करण्यासाठी समुपदेशक निवडा." },
  "All": { hi: "सभी", mr: "सर्व" },
  "Wellness Counselor": { hi: "वेलनेस काउंसलर", mr: "वेलनेस समुपदेशक" },
  "No counselors found for this language filter.": { hi: "इस भाषा फिल्टर के लिए कोई काउंसलर नहीं मिला।", mr: "या भाषा फिल्टरसाठी कोणतेही समुपदेशक सापडले नाहीत." },
  "Upcoming Sessions": { hi: "आगामी सत्र", mr: "आगामी सत्रे" },
  "For:": { hi: "के लिए:", mr: "साठी:" },
  "Join Meeting": { hi: "मीटिंग जॉइन करें", mr: "मीटिंग जॉइन करा" },
  "Reschedule slot": { hi: "स्लॉट रीशेड्यूल", mr: "स्लॉट पुन्हा ठरवा" },
  "Saving...": { hi: "सेव हो रहा है...", mr: "सेव्ह होत आहे..." },
  "Apply": { hi: "लागू करें", mr: "लागू करा" },
  "No upcoming sessions yet. Book one from the panel.": { hi: "अभी कोई आगामी सत्र नहीं है। पैनल से एक बुक करें।", mr: "अजून कोणतेही आगामी सत्र नाही. पॅनेलमधून एक बुक करा." },
  "Book Appointment": { hi: "अपॉइंटमेंट बुक करें", mr: "अपॉइंटमेंट बुक करा" },
  "Selected Counselor": { hi: "चयनित काउंसलर", mr: "निवडलेला समुपदेशक" },
  "Preferred Date": { hi: "पसंदीदा तारीख", mr: "पसंतीची तारीख" },
  "Preferred Slot": { hi: "पसंदीदा स्लॉट", mr: "पसंतीचा स्लॉट" },
  "Choose an available slot...": { hi: "उपलब्ध स्लॉट चुनें...", mr: "उपलब्ध स्लॉट निवडा..." },
  "Session Mode": { hi: "सेशन मोड", mr: "सत्र मोड" },
  "Location (if applicable)": { hi: "स्थान (यदि लागू हो)", mr: "ठिकाण (लागू असल्यास)" },
  "E.g., Clinic Name, Zoom": { hi: "जैसे, क्लिनिक नाम, ज़ूम", mr: "उदा., क्लिनिकचे नाव, झूम" },
  "Session Notes": { hi: "सेशन नोट्स", mr: "सत्र नोंदी" },
  "Topics you'd like to discuss...": { hi: "वे विषय जिन पर आप बात करना चाहते हैं...", mr: "तुम्हाला चर्चा करायचे विषय..." },
  "Booking...": { hi: "बुकिंग हो रही है...", mr: "बुकिंग होत आहे..." },
  "Confirm Booking": { hi: "बुकिंग कन्फर्म करें", mr: "बुकिंग निश्चित करा" },
  "Select a Counselor": { hi: "काउंसलर चुनें", mr: "समुपदेशक निवडा" },
  "Choose a counselor from the list to view their schedule and begin booking.": {
    hi: "उनका शेड्यूल देखने और बुकिंग शुरू करने के लिए सूची से काउंसलर चुनें।",
    mr: "वेळापत्रक पाहण्यासाठी आणि बुकिंग सुरू करण्यासाठी यादीतून समुपदेशक निवडा.",
  },
  "Open Slots": { hi: "खुले स्लॉट", mr: "उघडे स्लॉट" },
  "available": { hi: "उपलब्ध", mr: "उपलब्ध" },
  "No open slots currently available.": { hi: "अभी कोई खुला स्लॉट उपलब्ध नहीं है।", mr: "सध्या कोणतेही खुले स्लॉट उपलब्ध नाहीत." },
  "Session Prep Checklist": { hi: "सेशन तैयारी चेकलिस्ट", mr: "सत्र तयारी तपशील" },
  "No checklist items yet.": { hi: "अभी कोई चेकलिस्ट आइटम नहीं।", mr: "अजून कोणतेही तपशील नाहीत." },
  "Resources": { hi: "संसाधन", mr: "संसाधने" },
  "Explore our curated library of mental wellness guides, articles, and tools.": {
    hi: "मानसिक वेलनेस गाइड, लेख और टूल्स की हमारी चुनी हुई लाइब्रेरी देखें।",
    mr: "मानसिक वेलनेस मार्गदर्शक, लेख आणि साधनांची आमची निवडक लायब्ररी पाहा.",
  },
  "Failed to load resources.": { hi: "संसाधन लोड नहीं हो सके।", mr: "संसाधने लोड करता आली नाहीत." },
  "Failed to load library.": { hi: "लाइब्रेरी लोड नहीं हो सकी।", mr: "लायब्ररी लोड करता आली नाही." },
  "items": { hi: "आइटम", mr: "घटक" },
  "Search resources...": { hi: "संसाधन खोजें...", mr: "संसाधने शोधा..." },
  "All Types": { hi: "सभी प्रकार", mr: "सर्व प्रकार" },
  "Recommended": { hi: "सुझावित", mr: "शिफारसीय" },
  "No resources found": { hi: "कोई संसाधन नहीं मिला", mr: "कोणतीही संसाधने सापडली नाहीत" },
  "Try adjusting your filters or search query.": { hi: "अपने फिल्टर या खोज को बदलकर देखें।", mr: "तुमचे फिल्टर्स किंवा शोध बदलून पहा." },
  "Curated": { hi: "चुना हुआ", mr: "निवडक" },
  "Flexible": { hi: "लचीला", mr: "लवचिक" },
  "All Levels": { hi: "सभी स्तर", mr: "सर्व स्तर" },
  "resource": { hi: "संसाधन", mr: "संसाधन" },
  "Events": { hi: "इवेंट्स", mr: "कार्यक्रम" },
  "Register for workshops, masterclasses, and community circles.": {
    hi: "वर्कशॉप, मास्टरक्लास और कम्युनिटी सर्कल के लिए रजिस्टर करें।",
    mr: "वर्कशॉप, मास्टरक्लास आणि कम्युनिटी सर्कलसाठी नोंदणी करा.",
  },
  "Failed to load events.": { hi: "इवेंट्स लोड नहीं हो सके।", mr: "कार्यक्रम लोड करता आले नाहीत." },
  "Unable to update registration.": { hi: "रजिस्ट्रेशन अपडेट नहीं हो सका।", mr: "नोंदणी अपडेट करता आली नाही." },
  "Featured Event": { hi: "फीचर्ड इवेंट", mr: "ठळक कार्यक्रम" },
  "Join Featured Event": { hi: "फीचर्ड इवेंट जॉइन करें", mr: "ठळक कार्यक्रमात सामील व्हा" },
  "Workshops": { hi: "वर्कशॉप", mr: "वर्कशॉप" },
  "Masterclasses": { hi: "मास्टरक्लास", mr: "मास्टरक्लास" },
  "Community Circles": { hi: "कम्युनिटी सर्कल", mr: "कम्युनिटी सर्कल" },
  "Event": { hi: "इवेंट", mr: "कार्यक्रम" },
  "Host:": { hi: "होस्ट:", mr: "होस्ट:" },
  "seats": { hi: "सीट", mr: "जागा" },
  "Processing...": { hi: "प्रोसेस हो रहा है...", mr: "प्रक्रिया सुरू आहे..." },
  "Reserve Spot": { hi: "स्थान सुरक्षित करें", mr: "जागा राखून ठेवा" },
  "Waitlisting...": { hi: "वेटलिस्ट में जोड़ा जा रहा है...", mr: "वेटलिस्टमध्ये जोडले जात आहे..." },
  "Join Waitlist": { hi: "वेटलिस्ट जॉइन करें", mr: "वेटलिस्टमध्ये सामील व्हा" },
  "Weekly Lineup": { hi: "साप्ताहिक लाइनअप", mr: "साप्ताहिक सूची" },
  "No lineup scheduled.": { hi: "कोई लाइनअप तय नहीं है।", mr: "कोणतीही सूची नियोजित नाही." },
  "Privacy Reminder": { hi: "गोपनीयता याद दिलाना", mr: "गोपनीयता स्मरण" },
  "Participation details remain completely confidential and are visible only within the dedicated wellness support team.": {
    hi: "भागीदारी का विवरण पूरी तरह गोपनीय रहता है और केवल समर्पित वेलनेस सपोर्ट टीम को दिखाई देता है।",
    mr: "सहभागाचे तपशील पूर्णपणे गोपनीय राहतात आणि फक्त वेलनेस सपोर्ट टीमलाच दिसतात.",
  },
  "Community": { hi: "समुदाय", mr: "समुदाय" },
  "A safe space to share stories, support each other, and grow together.": {
    hi: "कहानियाँ साझा करने, एक-दूसरे का साथ देने और साथ में आगे बढ़ने के लिए एक सुरक्षित जगह।",
    mr: "कथा शेअर करण्यासाठी, एकमेकांना आधार देण्यासाठी आणि एकत्र वाढण्यासाठी सुरक्षित जागा.",
  },
  "Failed to load community.": { hi: "समुदाय लोड नहीं हो सका।", mr: "समुदाय लोड करता आला नाही." },
  "Title cannot be empty.": { hi: "शीर्षक खाली नहीं हो सकता।", mr: "शीर्षक रिकामे असू शकत नाही." },
  "Body cannot be empty.": { hi: "संदेश खाली नहीं हो सकता।", mr: "मजकूर रिकामा असू शकत नाही." },
  "Unable to create post.": { hi: "पोस्ट बनाई नहीं जा सकी।", mr: "पोस्ट तयार करता आली नाही." },
  "Unable to vote.": { hi: "वोट नहीं किया जा सका।", mr: "मत देता आले नाही." },
  "Posts": { hi: "पोस्ट", mr: "पोस्ट" },
  "Comments": { hi: "कमेंट", mr: "प्रतिक्रिया" },
  "Create a Post": { hi: "पोस्ट बनाएं", mr: "पोस्ट तयार करा" },
  "Share your thoughts with the community.": { hi: "अपने विचार समुदाय के साथ साझा करें।", mr: "तुमचे विचार समुदायासोबत शेअर करा." },
  "Your display name": { hi: "आपका डिस्प्ले नाम", mr: "तुमचे दिसणारे नाव" },
  "Your role (e.g. Member, Peer)": { hi: "आपकी भूमिका (जैसे सदस्य, पीयर)", mr: "तुमची भूमिका (उदा. सदस्य, सहकारी)" },
  "Post title": { hi: "पोस्ट शीर्षक", mr: "पोस्ट शीर्षक" },
  "What’s on your mind? Share context, what you’ve tried, and what you need help with...": {
    hi: "आपके मन में क्या है? संदर्भ, आपने क्या कोशिश की है, और किस बात में मदद चाहिए, यह साझा करें...",
    mr: "तुमच्या मनात काय आहे? संदर्भ, तुम्ही काय प्रयत्न केले आणि कशात मदत हवी आहे ते शेअर करा...",
  },
  "Publishing...": { hi: "पब्लिश हो रहा है...", mr: "प्रकाशित होत आहे..." },
  "Publish Post": { hi: "पोस्ट प्रकाशित करें", mr: "पोस्ट प्रकाशित करा" },
  "Newest": { hi: "नवीनतम", mr: "नवीनतम" },
  "Top Voted": { hi: "सबसे अधिक वोट", mr: "सर्वाधिक मत" },
  "All topics": { hi: "सभी विषय", mr: "सर्व विषय" },
  "Search discussions...": { hi: "चर्चाएँ खोजें...", mr: "चर्चा शोधा..." },
  "No posts found": { hi: "कोई पोस्ट नहीं मिली", mr: "कोणतीही पोस्ट सापडली नाही" },
  "Be the first to start a conversation.": { hi: "बातचीत शुरू करने वाले पहले व्यक्ति बनें।", mr: "संवाद सुरू करणारे पहिले बना." },
  "general": { hi: "सामान्य", mr: "सामान्य" },
  "Just now": { hi: "अभी", mr: "आत्ताच" },
  "Untitled": { hi: "बिना शीर्षक", mr: "शीर्षक नाही" },
  "Discussions": { hi: "चर्चाएँ", mr: "चर्चा" },
  "Reset vote": { hi: "वोट रीसेट करें", mr: "मत रीसेट करा" },
  "Support Groups": { hi: "सपोर्ट ग्रुप", mr: "सपोर्ट गट" },
  "Next:": { hi: "अगला:", mr: "पुढील:" },
  "TBD": { hi: "निर्धारित होना बाकी", mr: "नंतर ठरेल" },
  "Browse all groups": { hi: "सभी समूह देखें", mr: "सर्व गट पाहा" },
  "Mentors": { hi: "मेंटर्स", mr: "मार्गदर्शक" },
  "Mentor": { hi: "मेंटोर", mr: "मार्गदर्शक" },
  "Aura AI Context": { hi: "ऑरा एआई कॉन्टेक्स्ट", mr: "ऑरा एआय संदर्भ" },
  "Your intelligent mental wellness assistant with direct access to your habits and sessions.": {
    hi: "आपका बुद्धिमान मानसिक वेलनेस सहायक, जिसे आपकी आदतों और सत्रों तक सीधी पहुँच है।",
    mr: "तुमचा बुद्धिमान मानसिक वेलनेस सहाय्यक, ज्याला तुमच्या सवयी आणि सत्रांचा थेट संदर्भ आहे.",
  },
  "Failed to load chat history": { hi: "चैट इतिहास लोड नहीं हो सका", mr: "चॅट इतिहास लोड करता आला नाही" },
  "Failed to create conversation": { hi: "बातचीत शुरू नहीं हो सकी", mr: "संवाद तयार करता आला नाही" },
  "Failed to send message": { hi: "संदेश भेजा नहीं जा सका", mr: "संदेश पाठवता आला नाही" },
  "Conversation": { hi: "बातचीत", mr: "संवाद" },
  "Not started yet": { hi: "अभी शुरू नहीं", mr: "अजून सुरू नाही" },
  "Latest": { hi: "नवीनतम", mr: "नवीनतम" },
  "New Chat": { hi: "नई चैट", mr: "नवीन चॅट" },
  "Syncing context...": { hi: "कॉन्टेक्स्ट सिंक हो रहा है...", mr: "संदर्भ सिंक होत आहे..." },
  "Inhale for 4s, Hold for 7s, Exhale for 8s": { hi: "4 सेकंड सांस लें, 7 सेकंड रोकें, 8 सेकंड छोड़ें", mr: "4 सेकंद श्वास घ्या, 7 सेकंद थांबा, 8 सेकंद श्वास सोडा" },
  "5-4-3-2-1 Grounding": { hi: "5-4-3-2-1 ग्राउंडिंग", mr: "5-4-3-2-1 ग्राउंडिंग" },
  "Created Habit:": { hi: "आदत बनाई गई:", mr: "सवय तयार झाली:" },
  "Completed:": { hi: "पूरा हुआ:", mr: "पूर्ण:" },
  "Aura utilized": { hi: "ऑरा ने उपयोग किया", mr: "ऑराने वापरले" },
  "Aura is thinking": { hi: "ऑरा सोच रही है", mr: "ऑरा विचार करत आहे" },
  "Streaming": { hi: "स्ट्रीमिंग", mr: "स्ट्रीमिंग" },
  "Data retrieved.": { hi: "डेटा प्राप्त हुआ।", mr: "डेटा मिळाला." },
  "How can Aura help today?": { hi: "आज ऑरा कैसे मदद कर सकती है?", mr: "आज ऑरा कशी मदत करू शकते?" },
  "Start a conversation. Aura has access to your habits, appointments, and can guide you through immediate wellness exercises.": {
    hi: "बातचीत शुरू करें। ऑरा को आपकी आदतों और अपॉइंटमेंट की जानकारी है और वह तुरंत वेलनेस अभ्यास में मार्गदर्शन कर सकती है।",
    mr: "संवाद सुरू करा. ऑराला तुमच्या सवयी आणि अपॉइंटमेंटची माहिती आहे आणि ती तुम्हाला त्वरित वेलनेस व्यायामात मार्गदर्शन करू शकते.",
  },
  "I'm overwhelmed": { hi: "मैं बहुत परेशान हूँ", mr: "मी खूप गोंधळलेलो आहे" },
  "Create a stretching habit": { hi: "स्ट्रेचिंग की आदत बनाओ", mr: "स्ट्रेचिंगची सवय तयार करा" },
  "Check my schedule": { hi: "मेरा शेड्यूल देखें", mr: "माझे वेळापत्रक पाहा" },
  "Message Aura...": { hi: "ऑरा को संदेश भेजें...", mr: "ऑराला संदेश पाठवा..." },
  "Exercises & Habits": { hi: "अभ्यास और आदतें", mr: "व्यायाम आणि सवयी" },
  "Your interactive wellbeing routines and daily tracking.": {
    hi: "आपकी इंटरैक्टिव वेलबीइंग रूटीन और दैनिक ट्रैकिंग।",
    mr: "तुमच्या इंटरअॅक्टिव वेलबीइंग रूटीन आणि दैनंदिन ट्रॅकिंग.",
  },
  "Failed to load habit tracker.": { hi: "हैबिट ट्रैकर लोड नहीं हो सका।", mr: "हॅबिट ट्रॅकर लोड करता आला नाही." },
  "Could not load onboarding questions.": { hi: "ऑनबोर्डिंग प्रश्न लोड नहीं हो सके।", mr: "ऑनबोर्डिंग प्रश्न लोड करता आले नाहीत." },
  "Could not update habit.": { hi: "आदत अपडेट नहीं हो सकी।", mr: "सवय अपडेट करता आली नाही." },
  "Habit coach request failed.": { hi: "हैबिट कोच अनुरोध असफल रहा।", mr: "हॅबिट कोच विनंती अयशस्वी झाली." },
  "Habit title is required.": { hi: "आदत का शीर्षक आवश्यक है।", mr: "सवयीचे शीर्षक आवश्यक आहे." },
  "Could not create habit.": { hi: "आदत बनाई नहीं जा सकी।", mr: "सवय तयार करता आली नाही." },
  "Could not delete habit.": { hi: "आदत हटाई नहीं जा सकी।", mr: "सवय हटवता आली नाही." },
  "Could not save onboarding.": { hi: "ऑनबोर्डिंग सेव नहीं हो सका।", mr: "ऑनबोर्डिंग सेव्ह करता आले नाही." },
  "Quick Habit Setup": { hi: "त्वरित आदत सेटअप", mr: "झटपट सवय सेटअप" },
  "Answer these questions once. We will auto-create a starter habit plan for you.": {
    hi: "इन सवालों का जवाब एक बार दें। हम आपके लिए शुरुआती आदत योजना अपने आप बना देंगे।",
    mr: "या प्रश्नांची एकदाच उत्तरे द्या. आम्ही तुमच्यासाठी प्रारंभिक सवय योजना आपोआप तयार करू.",
  },
  "Loading questions...": { hi: "प्रश्न लोड हो रहे हैं...", mr: "प्रश्न लोड होत आहेत..." },
  "Creating your habits...": { hi: "आपकी आदतें बनाई जा रही हैं...", mr: "तुमच्या सवयी तयार होत आहेत..." },
  "Create My Starter Habits": { hi: "मेरी शुरुआती आदतें बनाएं", mr: "माझ्या प्रारंभिक सवयी तयार करा" },
  "Total Habits": { hi: "कुल आदतें", mr: "एकूण सवयी" },
  "Completed": { hi: "पूर्ण", mr: "पूर्ण" },
  "Pending": { hi: "लंबित", mr: "प्रलंबित" },
  "All tracked routines": { hi: "सभी ट्रैक की गई रूटीन", mr: "सर्व ट्रॅक केलेल्या दिनचर्या" },
  "Marked done": { hi: "पूरा चिह्नित", mr: "पूर्ण म्हणून चिन्हांकित" },
  "Still to complete": { hi: "अभी पूरा करना बाकी", mr: "अजून पूर्ण करायचे" },
  "Add New Habit": { hi: "नई आदत जोड़ें", mr: "नवीन सवय जोडा" },
  "Habit title": { hi: "आदत शीर्षक", mr: "सवयीचे शीर्षक" },
  "Description (optional)": { hi: "विवरण (वैकल्पिक)", mr: "वर्णन (पर्यायी)" },
  "Schedule (e.g. Morning)": { hi: "शेड्यूल (जैसे सुबह)", mr: "वेळापत्रक (उदा. सकाळ)" },
  "Category (e.g. sleep)": { hi: "श्रेणी (जैसे नींद)", mr: "श्रेणी (उदा. झोप)" },
  "Adding...": { hi: "जोड़ा जा रहा है...", mr: "जोडले जात आहे..." },
  "Add Habit": { hi: "आदत जोड़ें", mr: "सवय जोडा" },
  "Today’s Checklist": { hi: "आज की चेकलिस्ट", mr: "आजची यादी" },
  "done": { hi: "पूरा", mr: "पूर्ण" },
  "No habits tracked today.": { hi: "आज कोई आदत ट्रैक नहीं हुई।", mr: "आज कोणतीही सवय ट्रॅक झालेली नाही." },
  "Delete": { hi: "हटाएं", mr: "हटवा" },
  "Weekly Completion": { hi: "साप्ताहिक पूर्णता", mr: "साप्ताहिक पूर्णता" },
  "Category Progress": { hi: "श्रेणी प्रगति", mr: "श्रेणी प्रगती" },
  "No category data available yet.": { hi: "अभी श्रेणी डेटा उपलब्ध नहीं है।", mr: "अजून श्रेणी डेटा उपलब्ध नाही." },
  "Calendar Overview": { hi: "कैलेंडर सारांश", mr: "कॅलेंडर आढावा" },
  "AI Habit Coach": { hi: "एआई हैबिट कोच", mr: "एआय हॅबिट कोच" },
  "Describe your blocker or goal": { hi: "अपनी रुकावट या लक्ष्य बताएं", mr: "तुमची अडचण किंवा उद्दिष्ट सांगा" },
  "Example: I keep missing my sleep routine during exam week.": {
    hi: "उदाहरण: परीक्षा सप्ताह में मैं अपनी नींद की दिनचर्या चूक जाता हूँ।",
    mr: "उदाहरण: परीक्षेच्या आठवड्यात माझी झोपेची दिनचर्या चुकते.",
  },
  "Generating plan...": { hi: "योजना बन रही है...", mr: "योजना तयार होत आहे..." },
  "Get personalized plan": { hi: "व्यक्तिगत योजना पाएं", mr: "वैयक्तिक योजना मिळवा" },
  "Your current habits context": { hi: "आपकी वर्तमान आदतों का संदर्भ", mr: "तुमच्या सध्याच्या सवयींचा संदर्भ" },
  "Focus:": { hi: "फोकस:", mr: "लक्ष:" },
  "Confidence:": { hi: "विश्वास:", mr: "विश्वास:" },
  "Suggested Actions": { hi: "सुझाए गए कदम", mr: "सुचवलेल्या कृती" },
  "Ready for analysis": { hi: "विश्लेषण के लिए तैयार", mr: "विश्लेषणासाठी तयार" },
  "Ask the AI coach for a personalized plan based on your current habit data.": {
    hi: "अपनी वर्तमान आदतों के डेटा के आधार पर एआई कोच से व्यक्तिगत योजना मांगें।",
    mr: "तुमच्या सध्याच्या सवयींच्या डेटावर आधारित एआय कोचकडून वैयक्तिक योजना मागा.",
  },
  "Practitioner Overview": { hi: "प्रैक्टिशनर सारांश", mr: "प्रॅक्टिशनर आढावा" },
  "Here's a snapshot of your workload today.": { hi: "आज के आपके काम का एक त्वरित सारांश।", mr: "आजच्या कामाचा झटपट आढावा." },
  "Sessions": { hi: "सत्र", mr: "सत्रे" },
  "Pending": { hi: "लंबित", mr: "प्रलंबित" },
  "Total": { hi: "कुल", mr: "एकूण" },
  "Today's Schedule": { hi: "आज का शेड्यूल", mr: "आजचे वेळापत्रक" },
  "View All →": { hi: "सभी देखें →", mr: "सर्व पहा →" },
  "Online": { hi: "ऑनलाइन", mr: "ऑनलाइन" },
  "Confirmed": { hi: "कन्फर्म", mr: "निश्चित" },
  "Dossier": { hi: "डॉसियर", mr: "डॉसिअर" },
  "No sessions scheduled today.": { hi: "आज कोई सत्र निर्धारित नहीं है।", mr: "आज कोणतीही सत्रे नियोजित नाहीत." },
  "Action Items": { hi: "कार्य आइटम", mr: "कृती आयटम" },
  "Pending": { hi: "लंबित", mr: "प्रलंबित" },
  "Review Request": { hi: "अनुरोध देखें", mr: "विनंती पाहा" },
  "You are all caught up!": { hi: "आपने सब पूरा कर लिया है!", mr: "तुम्ही सर्व पूर्ण केले आहे!" },
  "Inbox": { hi: "इनबॉक्स", mr: "इनबॉक्स" },
  "Admin Overview": { hi: "एडमिन सारांश", mr: "अ‍ॅडमिन आढावा" },
  "Welcome back. Use the sidebar to navigate through user management, moderation, and alerts.": {
    hi: "वापसी पर स्वागत है। यूज़र मैनेजमेंट, मॉडरेशन और अलर्ट्स के लिए साइडबार का उपयोग करें।",
    mr: "पुन्हा स्वागत आहे. वापरकर्ता व्यवस्थापन, मॉडरेशन आणि अलर्ट्ससाठी साइडबार वापरा.",
  },
  "Total Users": { hi: "कुल उपयोगकर्ता", mr: "एकूण वापरकर्ते" },
  "Active Therapists": { hi: "सक्रिय थेरपिस्ट", mr: "सक्रिय थेरपिस्ट" },
  "Unresolved Alerts": { hi: "अनसुलझे अलर्ट्स", mr: "न सुटलेले अलर्ट" },
  "No upcoming events found for this category.": { hi: "इस श्रेणी के लिए कोई आगामी इवेंट नहीं मिला।", mr: "या श्रेणीसाठी कोणतेही आगामी कार्यक्रम सापडले नाहीत." },
  "Resource Library": { hi: "रिसोर्स लाइब्रेरी", mr: "संसाधन लायब्ररी" },
  "Curate and dispatch clinical exercises directly to patient portals.": { hi: "क्लिनिकल अभ्यास चुनें और सीधे मरीज पोर्टल पर भेजें।", mr: "क्लिनिकल व्यायाम निवडा आणि थेट रुग्ण पोर्टलवर पाठवा." },
  "User Management": { hi: "यूज़र मैनेजमेंट", mr: "वापरकर्ता व्यवस्थापन" },
  "View, monitor, and manage the access of registered users across the platform.": { hi: "पूरे प्लेटफ़ॉर्म पर पंजीकृत उपयोगकर्ताओं की पहुँच देखें, मॉनिटर करें और प्रबंधित करें।", mr: "संपूर्ण प्लॅटफॉर्मवरील नोंदणीकृत वापरकर्त्यांचा प्रवेश पाहा, निरीक्षण करा आणि व्यवस्थापित करा." },
  "Resource Library Management": { hi: "रिसोर्स लाइब्रेरी मैनेजमेंट", mr: "संसाधन लायब्ररी व्यवस्थापन" },
  "Curate and organize psychoeducational literature, hotlines, and media.": { hi: "साइकोएजुकेशनल सामग्री, हेल्पलाइन और मीडिया को व्यवस्थित करें।", mr: "सायकोएज्युकेशनल साहित्य, हेल्पलाइन आणि मीडिया व्यवस्थापित करा." },
  "Therapist Management": { hi: "थेरपिस्ट मैनेजमेंट", mr: "थेरपिस्ट व्यवस्थापन" },
  "Add, view, and manage verified mental health professionals.": { hi: "वेरिफाइड मानसिक स्वास्थ्य पेशेवर जोड़ें, देखें और प्रबंधित करें।", mr: "पडताळलेले मानसिक आरोग्य व्यावसायिक जोडा, पहा आणि व्यवस्थापित करा." },
  "Manage your schedule, respond to requests, and update sessions.": { hi: "अपना शेड्यूल संभालें, अनुरोधों का जवाब दें और सत्र अपडेट करें।", mr: "तुमचे वेळापत्रक सांभाळा, विनंत्यांना प्रतिसाद द्या आणि सत्रे अपडेट करा." },
  "Moderation Queue": { hi: "मॉडरेशन कतार", mr: "मॉडरेशन रांग" },
  "Review community posts automatically flagged by AI for harmful or abusive content.": { hi: "हानिकारक या अपमानजनक सामग्री के लिए एआई द्वारा फ्लैग की गई कम्युनिटी पोस्ट की समीक्षा करें।", mr: "हानिकारक किंवा अपमानास्पद मजकुरासाठी एआयने चिन्हांकित केलेल्या समुदाय पोस्टचे पुनरावलोकन करा." },
  "Event Management": { hi: "इवेंट मैनेजमेंट", mr: "कार्यक्रम व्यवस्थापन" },
  "Organize and publish workshops, webinars, and group sessions.": { hi: "वर्कशॉप, वेबिनार और समूह सत्रों का आयोजन और प्रकाशन करें।", mr: "वर्कशॉप, वेबिनार आणि गट सत्रांचे आयोजन आणि प्रकाशन करा." },
  "Critical Alerts Console": { hi: "क्रिटिकल अलर्ट्स कंसोल", mr: "महत्त्वपूर्ण अलर्ट कन्सोल" },
  "High-priority notifications triggered by AI diagnostics indicating immediate clinical crises.": { hi: "तत्काल क्लिनिकल संकट दर्शाने वाले एआई डायग्नोस्टिक्स से ट्रिगर हुई उच्च-प्राथमिकता सूचनाएँ।", mr: "तातडीच्या क्लिनिकल संकटांकडे सूचित करणाऱ्या एआय निदानांमुळे ट्रिगर झालेल्या उच्च-प्राधान्य सूचना." },
  "Patient Directory": { hi: "मरीज निर्देशिका", mr: "रुग्ण निर्देशिका" },
  "Manage and monitor the individuals assigned to your care.": { hi: "आपकी देखरेख में सौंपे गए व्यक्तियों को प्रबंधित और मॉनिटर करें।", mr: "तुमच्या देखरेखीखाली असलेल्या व्यक्ती व्यवस्थापित आणि निरीक्षण करा." },
  "Connect with your patients securely.": { hi: "अपने मरीजों से सुरक्षित रूप से जुड़ें।", mr: "तुमच्या रुग्णांशी सुरक्षितपणे संपर्क साधा." },
  "Search patients...": { hi: "मरीज खोजें...", mr: "रुग्ण शोधा..." },
};

function interpolate(text, replacements = {}) {
  return Object.entries(replacements).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value ?? "")),
    text
  );
}

function resolveTranslation(text, language, replacements) {
  const template = translations[text]?.[language] || text;
  return interpolate(template, replacements);
}

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("en");

  useEffect(() => {
    const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (stored && LANGUAGE_OPTIONS.some((option) => option.code === stored)) {
      setLanguage(stored);
    }
  }, []);

  useEffect(() => {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (text, replacements) => resolveTranslation(text, language, replacements),
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
